### PR TITLE
Added example WebAC turtle files

### PR DESCRIPTION
**Pull request by peichman-umd**
Taken from https://wiki.duraspace.org/display/FEDORA4x/WebAC+Authorization+Delegate

Using a dummy namespace (http://example.com/webac#) for the WebAcl class for now, this will most likely eventually be placed in a Fedora ontology.

### CODE REVIEW

**Comment by awoods** [comment]
This looks good.
As a side note, we need to go ahead and create the Fedora webac ontology. A proposal namespace:
http://fedora.info/definitions/v4/webac

Would someone be interested in taking the task of creating the RDF?

**Comment by acoburn** [comment]
:+1:

**Comment by whikloj** [comment]
:+1:

**Comment by whikloj** [comment]
Resolved with aa6d9a20bb66b7b2726201024caa0da78cdfaf49

**Pull request closed without merging**
