### PR TITLE
added skeleton for IT tests

### PR DESCRIPTION
**Pull request by acoburn**
This add a basic skeleton for integration testing.

### CODE REVIEW

**Comment by awoods** [comment]
I recently updated fcrepo-webapp-plus to make the configuration more consistent:
https://github.com/fcrepo4-exts/fcrepo-webapp-plus/commit/81fd433c7e861668bda3bb20a4930b1d843bbab8

It looks like the source of your setup came from the same well as the ones that needed to be updated in fcrepo-webapp-plus. Please use the more consistent set from the commit above... if possible.

**Comment by acoburn** [comment]
@awoods I cleaned up the spring configuration a bit. Is that what you had in mind?

**Comment by awoods** [comment]
Yes. Thanks, @acoburn.

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4-labs/fcrepo-module-auth-webac/commit/a5cb58ae4063c0482e0c050d546bb6dd8e0c62da

**Pull request closed without merging**
